name: dockerhub-TinyTeX-hithesis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pull docker image
      run: |
        docker pull dustincys/tinytex-hithesis
        
    - name: Test thesis
      run: |
        docker run --rm -i -v "$PWD":/home/runner dustincys/tinytex-hithesis:v1.0.0 make thesis
    - name: Test doc
      run: |
        docker run --rm -i -v "$PWD":/home/runner dustincys/tinytex-hithesis:v1.0.0 make doc
