name: ubuntu-dockerhub-TinyTeX-hithesis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pull docker image
      run: |
        docker pull dustincys/tinytex-hithesis:latest

    - name: Test doc
      run: |
        docker run --rm -i -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest make doc
    - name: Test chinese thesis
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitbook/chinese
        docker run --rm -i -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest make thesis
        cd $CURRENTDIR
    - name: Test english thesis
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitbook/english
        docker run --rm -i -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest make thesis
        cd $CURRENTDIR
    - name: Test reports
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitart/reports
        docker run --rm -i -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest make report
        cd $CURRENTDIR
    - name: Test reportplus
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitart/reportplus
        docker run --rm -i -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest make report
        cd $CURRENTDIR
